(function(){var d=true,e=false;if(!window.google)window.google={};google.g=function(a,b,c){a.addEventListener?a.addEventListener(b,c,e):a.attachEvent("on"+b,c)};google.i=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,e):a.detachEvent("on"+b,c)};google.a={};google.a.c={d:e,m:e,p:e,e:e};google.a.product={d:e,l:e,o:e,n:e,k:e,e:e};google.a.c.version="";google.a.product.version="";google.a.init=function(a){var b=null,c=null;if(window.opera){google.a.c.e=d;google.a.product.e=d;b=c=/Opera\/(\S+)/}else if(a.indexOf("MSIE")!=-1){google.a.c.d=d;google.a.product.d=d;b=c=/MSIE\s+([^\);]+)(\)|;)/}else if(a.indexOf("WebKit")!=-1){google.a.c.p=d;if(a.indexOf("Chrome")!=-1){google.a.product.k=d;c=/Chrome\/(\S+)/}else if(a.indexOf("iPad")!=-1){google.a.product.n=d;c=/Version\/(\S+)/}else if(a.indexOf("Safari")!=-1){google.a.product.o=d;c=/Version\/(\S+)/}b=/WebKit\/(\S+)/}else if(a.indexOf("Gecko")!=-1){google.a.c.m=d;if(a.indexOf("Firefox")!=-1){google.a.product.l=d;c=/Firefox\/(\S+)/}b=/rv\:([^\);]+)(\)|;)/}if(b){b=b.exec(a);google.a.c.version=b?b[1]:""}if(c){b=c.exec(a);google.a.product.version=b?b[1]:""}};google.a.init(window.navigator.userAgent);google.a.h=function(a,b){function c(t,u){if(t<u)return-1;else if(t>u)return 1;return 0}for(var f=0,v=a.replace(/^\s+|\s+$/g,"").split("."),w=b.replace(/^\s+|\s+$/g,"").split("."),z=Math.max(v.length,w.length),l=0;f==0&&l<z;l++){var A=v[l]||"",B=w[l]||"",C=RegExp("(\\d*)(\\D*)","g"),D=RegExp("(\\d*)(\\D*)","g");do{var g=C.exec(A)||["","",""],h=D.exec(B)||["","",""];if(g[0].length==0&&h[0].length==0)break;f=g[1].length==0?0:parseInt(g[1],10);var E=h[1].length==0?0:parseInt(h[1],10);f=c(f,E)||c(g[2].length==0,h[2].length==0)||c(g[2],h[2])}while(f==0)}return f};google.a.s=function(a){return google.a.h(google.a.c.version,a)>=0};google.a.t=function(a){return google.a.h(google.a.product.version,a)>=0};try{if(!google.doodle)google.doodle={};var i,j,k,m,n=0,o,p=[0,68,117,166,211,234,275];google.doodle.init=function(){if(window.location.href.indexOf("#")==-1){j=document.getElementById("logo-hl");i=document.getElementById("cursor");if(j&&i)if(m)q(null);else{m=d;google.j&&google.j.en&&r(100,s,function(){return google.rein&&google.dstr});r(100,x,function(){return google.g&&google.a})}}};var

r=function(a,b,c){if(c())b();else a<200&&window.setTimeout(function(){r(a+1,b,c)},a)},
s=function(){if(!google.doodle.r){google.doodle.r=d;google.rein.push(google.doodle.init);google.dstr.push(y)}},
F=function(){return document.forms.f||document.forms.gs||document.forms.tsf},
G=function(){var a=F();return(a&&a.q&&a.q.value||"").length},
q=function(){var a=G();j.style.width=i.style.left=p[Math.min(a,p.length-1)]+"px";if(a!=n&&a<p.length){o&&window.clearInterval(o);H(e);H(d);o=window.setInterval(I,540)}n=a},
H=function(a){i.style.display=a?"inline":"none"},
I=function(){H(i.style.display=="none"&&G()>0)},
x=function(){k=google.a.c.d?"propertychange":"input";
var a=F();if(a){google.g(a,k,q);google.g(a,"keyup",q)}},
y=function(){var a=F();;if(a){google.i(a,k,q);google.i(a,"keyup",q)}o&&window.clearInterval(o);H(e);n=0}}catch(J){google.ml(J,e,{_sn:"KEY"})};})();google.doodle.init()